# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='AUTONUM',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='Slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='CATEGORY',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='category',
            name='NUMBER',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='category',
            name='PART_DESC',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='category',
            name='PART_NUM',
            field=models.TextField(default=' '),
        ),
    ]
